var lists = {
    random: ['students', 'artists', 'photographers', 'dancers', 'actors', 'bankers', 'magicians', 'doctors', 'lawyers', 'grannies', 'grandpas', 'aunties', 'uncles', 'nobodies', 'tramps', 'dogs', 'cats', 'elephants', 'binmen', 'celebrities', 'singer-songwriters', 'carjackers', 'jokers', 'surfers', 'Americans'],

    codenames: [
        'AFRICA',
        'AGENT',
        'AIR',
        'ALIEN',
        'ALPS',
        'AMAZON',
        'AMBULANCE',
        'AMERICA',
        'ANGEL',
        'ANTARCTICA',
        'APPLE',
        'ARM',
        'ATLANTIS',
        'AUSTRALIA',
        'AZTEC',
        'BACK',
        'BALL',
        'BAND',
        'BANK',
        'BAR',
        'BARK',
        'BAT',
        'BATTERY',
        'BEACH',
        'BEAR',
        'BEAT',
        'BED',
        'BEIJING',
        'BELL',
        'BELT',
        'BERLIN',
        'BERMUDA',
        'BERRY',
        'BILL',
        'BLOCK',
        'BOARD',
        'BOLT',
        'BOMB',
        'BOND',
        'BOOM',
        'BOOT',
        'BOTTLE',
        'BOW',
        'BOX',
        'BRIDGE',
        'BRUSH',
        'BUCK',
        'BUFFALO',
        'BUG',
        'BUGLE',
        'BUTTON',
        'CALF',
        'CANADA',
        'CAP',
        'CAPITAL',
        'CAR',
        'CARD',
        'CARROT',
        'CASINO',
        'CAST',
        'CAT',
        'CELL',
        'CENTAUR',
        'CENTER',
        'CHAIR',
        'CHANGE',
        'CHARGE',
        'CHECK',
        'CHEST',
        'CHICK',
        'CHINA',
        'CHOCOLATE',
        'CHURCH',
        'CIRCLE',
        'CLIFF',
        'CLOAK',
        'CLUB',
        'CODE',
        'COLD',
        'COMIC',
        'COMPOUND',
        'CONCERT',
        'CONDUCTOR',
        'CONTRACT',
        'COOK',
        'COPPER',
        'COTTON',
        'COURT',
        'COVER',
        'CRANE',
        'CRASH',
        'CRICKET',
        'CROSS',
        'CROWN',
        'CYCLE',
        'CZECH',
        'DANCE',
        'DATE',
        'DAY',
        'DEATH',
        'DECK',
        'DEGREE',
        'DIAMOND',
        'DICE',
        'DINOSAUR',
        'DISEASE',
        'DOCTOR',
        'DOG',
        'DRAFT',
        'DRAGON',
        'DRESS',
        'DRILL',
        'DROP',
        'DUCK',
        'DWARF',
        'EAGLE',
        'EGYPT',
        'EMBASSY',
        'ENGINE',
        'ENGLAND',
        'EUROPE',
        'EYE',
        'FACE',
        'FAIR',
        'FALL',
        'FAN',
        'FENCE',
        'FIELD',
        'FIGHTER',
        'FIGURE',
        'FILE',
        'FILM',
        'FIRE',
        'FISH',
        'FLUTE',
        'FLY',
        'FOOT',
        'FORCE',
        'FOREST',
        'FORK',
        'FRANCE',
        'GAME',
        'GAS',
        'GENIUS',
        'GERMANY',
        'GHOST',
        'GIANT',
        'GLASS',
        'GLOVE',
        'GOLD',
        'GRACE',
        'GRASS',
        'GREECE',
        'GREEN',
        'GROUND',
        'HAM',
        'HAND',
        'HAWK',
        'HEAD',
        'HEART',
        'HELICOPTER',
        'HIMALAYAS',
        'HOLE',
        'HOLLYWOOD',
        'HONEY',
        'HOOD',
        'HOOK',
        'HORN',
        'HORSE',
        'HORSESHOE',
        'HOSPITAL',
        'HOTEL',
        'ICE',
        'ICE CREAM',
        'INDIA',
        'IRON',
        'IVORY',
        'JACK',
        'JAM',
        'JET',
        'JUPITER',
        'KANGAROO',
        'KETCHUP',
        'KEY',
        'KID',
        'KING',
        'KIWI',
        'KNIFE',
        'KNIGHT',
        'LAB',
        'LAP',
        'LASER',
        'LAWYER',
        'LEAD',
        'LEMON',
        'LEPRECHAUN',
        'LIFE',
        'LIGHT',
        'LIMOUSINE',
        'LINE',
        'LINK',
        'LION',
        'LITTER',
        'LOCH NESS',
        'LOCK',
        'LOG',
        'LONDON',
        'LUCK',
        'MAIL',
        'MAMMOTH',
        'MAPLE',
        'MARBLE',
        'MARCH',
        'MASS',
        'MATCH',
        'MERCURY',
        'MEXICO',
        'MICROSCOPE',
        'MILLIONAIRE',
        'MINE',
        'MINT',
        'MISSILE',
        'MODEL',
        'MOLE',
        'MOON',
        'MOSCOW',
        'MOUNT',
        'MOUSE',
        'MOUTH',
        'MUG',
        'NAIL',
        'NEEDLE',
        'NET',
        'NEW YORK',
        'NIGHT',
        'NINJA',
        'NOTE',
        'NOVEL',
        'NURSE',
        'NUT',
        'OCTOPUS',
        'OIL',
        'OLIVE',
        'OLYMPUS',
        'OPERA',
        'ORANGE',
        'ORGAN',
        'PALM',
        'PAN',
        'PANTS',
        'PAPER',
        'PARACHUTE',
        'PARK',
        'PART',
        'PASS',
        'PASTE',
        'PENGUIN',
        'PHOENIX',
        'PIANO',
        'PIE',
        'PILOT',
        'PIN',
        'PIPE',
        'PIRATE',
        'PISTOL',
        'PIT',
        'PITCH',
        'PLANE',
        'PLASTIC',
        'PLATE',
        'PLATYPUS',
        'PLAY',
        'PLOT',
        'POINT',
        'POISON',
        'POLE',
        'POLICE',
        'POOL',
        'PORT',
        'POST',
        'POUND',
        'PRESS',
        'PRINCESS',
        'PUMPKIN',
        'PUPIL',
        'PYRAMID',
        'QUEEN',
        'RABBIT',
        'RACKET',
        'RAY',
        'REVOLUTION',
        'RING',
        'ROBIN',
        'ROBOT',
        'ROCK',
        'ROME',
        'ROOT',
        'ROSE',
        'ROULETTE',
        'ROUND',
        'ROW',
        'RULER',
        'SATELLITE',
        'SATURN',
        'SCALE',
        'SCHOOL',
        'SCIENTIST',
        'SCORPION',
        'SCREEN',
        'SCUBA DIVER',
        'SEAL',
        'SERVER',
        'SHADOW',
        'SHAKESPEARE',
        'SHARK',
        'SHIP',
        'SHOE',
        'SHOP',
        'SHOT',
        'SINK',
        'SKYSCRAPER',
        'SLIP',
        'SLUG',
        'SMUGGLER',
        'SNOW',
        'SNOWMAN',
        'SOCK',
        'SOLDIER',
        'SOUL',
        'SOUND',
        'SPACE',
        'SPELL',
        'SPIDER',
        'SPIKE',
        'SPINE',
        'SPOT',
        'SPRING',
        'SPY',
        'SQUARE',
        'STADIUM',
        'STAFF',
        'STAR',
        'STATE',
        'STICK',
        'STOCK',
        'STRAW',
        'STREAM',
        'STRIKE',
        'STRING',
        'SUB',
        'SUIT',
        'SUPERHERO',
        'SWING',
        'SWITCH',
        'TABLE',
        'TABLET',
        'TAG',
        'TAIL',
        'TAP',
        'TEACHER',
        'TELESCOPE',
        'TEMPLE',
        'THEATER',
        'THIEF',
        'THUMB',
        'TICK',
        'TIE',
        'TIME',
        'TOKYO',
        'TOOTH',
        'TORCH',
        'TOWER',
        'TRACK',
        'TRAIN',
        'TRIANGLE',
        'TRIP',
        'TRUNK',
        'TUBE',
        'TURKEY',
        'UNDERTAKER',
        'UNICORN',
        'VACUUM',
        'VAN',
        'VET',
        'WAKE',
        'WALL',
        'WAR',
        'WASHER',
        'WASHINGTON',
        'WATCH',
        'WATER',
        'WAVE',
        'WEB',
        'WELL',
        'WHALE',
        'WHIP',
        'WIND',
        'WITCH',
        'WORM',
        'YARD',
    ],

    harrypotter : [
        'Hannah Abbott',
        'Ludo Bagman',
        'Bathilda Bagshot',
        'Katie Bell',
        'Cuthbert Binns',
        'Phineas Nigellus Black',
        'Sirius Black',
        'Walburga Black',
        'Amelia Bones',
        'Susan Bones',
        'Terry Boot',
        'Lavender Brown',
        'Millicent Bulstrode',
        'Charity Burbage',
        'Frank Bryce',
        'Alecto Carrow',
        'Amycus Carrow',
        'Reginald Cattermole',
        'Mary Cattermole',
        'Cho Chang',
        'Penelope Clearwater',
        'Michael Corner',
        'Vincent Crabbe',
        'Colin Creevey',
        'Dennis Creevey',
        'Dirk Cresswell',
        'Barty Crouch Jr',
        'Roger Davies',
        'John Dawlish',
        'Fleur Delacour',
        'Gabrielle Delacour',
        'Dedalus Diggle',
        'Amos Diggory',
        'Cedric Diggory',
        'Elphias Doge',
        'Antonin Dolohov',
        'Aberforth Dumbledore',
        'Albus Dumbledore',
        'Ariana Dumbledore',
        'Kendra Dumbledore',
        'Percival Dumbledore',
        'Dudley Dursley',
        'Marge Dursley',
        'Petunia Dursley',
        'Vernon Dursley',
        'Marietta Edgecombe',
        'Arabella Figg',
        'Argus Filch',
        'Justin Finch-Fletchley',
        'Seamus Finnigan',
        'Nicolas Flamel',
        'Marcus Flint',
        'Mundungus Fletcher',
        'Filius Flitwick',
        'Florean Fortescue',
        'Cornelius Fudge',
        'Marvolo Gaunt',
        'Merope Gaunt',
        'Morfin Gaunt',
        'Anthony Goldstein',
        'Gregory Goyle',
        'Hermione Granger',
        'Gregorovitch',
        'Fenrir Greyback',
        'Gellert Grindelwald',
        'Wilhelmina Grubbly-Plank',
        'Godric Gryffindor',
        'Rubeus Hagrid',
        'Rolanda Hooch',
        'Mafalda Hopkirk',
        'Helga Hufflepuff',
        'Angelina Johnson',
        'Lee Jordan',
        'Bertha Jorkins',
        'Igor Karkaroff',
        'Viktor Krum',
        'Bellatrix Lestrange',
        'Gilderoy Lockhart',
        'Alice Longbottom',
        'Frank Longbottom',
        'Augusta Longbottom',
        'Neville Longbottom',
        'Luna Lovegood',
        'Xenophilius Lovegood',
        'Remus Lupin',
        'Teddy Lupin',
        'Walden Macnair',
        'Draco Malfoy',
        'Lucius Malfoy',
        'Narcissa Malfoy',
        'Scorpius Malfoy',
        'Madam Malkin',
        'Griselda Marchbanks',
        'Olympe Maxime',
        'Ernie Macmillan',
        'Minerva McGonagall',
        'Eloise Midgen',
        'Cormac McLaggen',
        'Graham Montague',
        'Alastor (Mad-Eye) Moody',
        'Theodore Nott',
        'Bob Ogden',
        'Garrick Ollivander',
        'Pansy Parkinson',
        'Padma Patil',
        'Parvati Patil',
        'Peter Pettigrew',
        'Antioch Peverell',
        'Cadmus Peverell',
        'Ignotus Peverell',
        'Irma Pince',
        'Sturgis Podmore',
        'Poppy Pomfrey',
        'Harry Potter',
        'James Potter',
        'Lily Potter',
        'Quirinus Quirrell',
        'Helena Ravenclaw',
        'The Grey Lady',
        'Rowena Ravenclaw',
        'Demelza Robins',
        'Augustus Rookwood',
        'Thorfinn Rowle',
        'Albert Runcorn',
        'Newt Scamander',
        'Rufus Scrimgeour',
        'Kingsley Shacklebolt',
        'Stan Shunpike',
        'Aurora Sinistra',
        'Rita Skeeter',
        'Horace Slughorn',
        'Salazar Slytherin',
        'Zacharias Smith',
        'Severus Snape',
        'Alicia Spinnet',
        'Pomona Sprout',
        'Pius Thicknesse',
        'Dean Thomas',
        'Andromeda Tonks',
        'Nymphadora Tonks',
        'Ted Tonks',
        'Sybill Trelawney',
        'Wilkie Twycross',
        'Dolores Umbridge',
        'Emmeline Vance',
        'Romilda Vane',
        'Lord Voldemort',
        'Moaning Myrtle',
        'Arthur Weasley',
        'Bill Weasley',
        'Charlie Weasley',
        'Fred Weasley',
        'George Weasley',
        'Ginny Weasley',
        'Molly Weasley',
        'Percy Weasley',
        'Ron Weasley',
        'Oliver Wood',
        'Corban Yaxley',
        'Blaise Zabini',
    ],
}
